import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import ThemeToggle from './ThemeToggle'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "heyadi.xyz - aditya's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        {/* <nav className="nav">
        <ul className="flex justify-center space-x-6">
          <li>
            <Link href="#" className="text-blue-500 hover:underline">
              Home
            </Link>
          </li>
          <li>
            <Link href="/POW" className="text-blue-500 hover:underline">
              POW
            </Link>
          </li>
          <li>
            <Link href="#" className="text-blue-500 hover:underline">
              Resume
            </Link>
          </li>
          <li>
            <Link href="#" className="text-blue-500 hover:underline">
              Blogs
            </Link>
          </li>
        </ul>
      </nav> */}
          {children}
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}

